title: "Mi PÃ¡gina Personal"
description: "Un sitio creado con el tema Architect de GitHub Pages"
theme: jekyll-theme-architect

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
